### PR TITLE
Fixed typo in PVC

### PR DESCRIPTION
**Pull request by lucasantarella**

### CODE REVIEW

**Comment by lucasantarella** [comment]
Hey, love the chart. Trying to use it on my own and noticed the typo that would cause installation to fail.

**Comment by kylelee24** [comment]
@lucasantarella Thanks for actually adding this. Hopefully @davidtannock can merge it back in. I applied the changes and my PVC is now bound (now showing emptydir). 

I'm curious why your installation failed though. For me, beanstalkd worked but just wouldn't persist data.

**Comment by davidtannock** [comment]
Sorry this took me so long. I don't know how I missed this.

**Comment by davidtannock** [comment]
Thanks for fixing this bug.

I've packaged v1.1.1 and updated the helm repo.

**Pull request merged**
